package com.civicresolve.controller;

import com.civicresolve.model.User; import com.civicresolve.repository.UserRepository;
import org.springframework.http.*; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.web.bind.annotation.*;
import org.springframework.web.server.ResponseStatusException; import java.util.*;

@RestController @RequestMapping("/api/management/authorities") public class AuthorityManagementController {
 private final UserRepository users; private final PasswordEncoder passwords;
 public AuthorityManagementController(UserRepository u,PasswordEncoder p){users=u;passwords=p;}
 private Map<String,Object> safe(User u){Map<String,Object> m=new LinkedHashMap<>();m.put("id",u.id);m.put("fullName",u.fullName);m.put("authorityId",u.authorityId==null?"":u.authorityId);m.put("email",u.email);m.put("phone",u.phone==null?"":u.phone);m.put("department",u.department==null?"":u.department);m.put("designation",u.designation==null?"":u.designation);m.put("assignedArea",u.assignedArea==null?"":u.assignedArea);m.put("active",u.active);return m;}
 @GetMapping public List<Map<String,Object>> all(){return users.findByRoleOrderByFullNameAsc("AUTHORITY").stream().map(this::safe).toList();}
 @PostMapping @ResponseStatus(HttpStatus.CREATED) public Map<String,Object> create(@RequestBody Map<String,String> b){String name=Objects.toString(b.get("fullName"),"").trim(),email=Objects.toString(b.get("email"),"").trim().toLowerCase(Locale.ROOT),password=Objects.toString(b.get("temporaryPassword"),"");if(name.isBlank()||name.length()>150||email.isBlank()||password.length()<8)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Name, email and a temporary password of at least 8 characters are required");if(users.findByEmail(email).isPresent())throw new ResponseStatusException(HttpStatus.CONFLICT,"Email already registered");User u=new User();u.fullName=name;u.email=email;u.passwordHash=passwords.encode(password);u.role="AUTHORITY";u.active=true;u.authorityId="AUTH-"+String.format("%04d",users.findByRoleOrderByFullNameAsc("AUTHORITY").size()+1);apply(u,b);users.save(u);return safe(u);}
 @PatchMapping("/{id}") public Map<String,Object> update(@PathVariable Long id,@RequestBody Map<String,String> b){User u=users.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Authority not found"));if(!"AUTHORITY".equals(u.role))throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Authority not found");apply(u,b);if(b.containsKey("active"))u.active=Boolean.parseBoolean(b.get("active"));if(b.containsKey("temporaryPassword")){String p=Objects.toString(b.get("temporaryPassword"),"");if(p.length()<8)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Temporary password must contain at least 8 characters");u.passwordHash=passwords.encode(p);}users.save(u);return safe(u);}
 private void apply(User u,Map<String,String>b){if(b.containsKey("phone"))u.phone=limited(b.get("phone"),30,"Phone");if(b.containsKey("department"))u.department=limited(b.get("department"),120,"Department");if(b.containsKey("designation"))u.designation=limited(b.get("designation"),120,"Designation");if(b.containsKey("assignedArea"))u.assignedArea=limited(b.get("assignedArea"),120,"Assigned area");}
 private String limited(String v,int max,String field){String s=Objects.toString(v,"").trim();if(s.length()>max)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,field+" is too long");return s.isBlank()?null:s;}
}
