package com.civicresolve.controller;

import com.civicresolve.model.*; import com.civicresolve.repository.*;
import org.springframework.http.*; import org.springframework.security.core.Authentication; import org.springframework.web.bind.annotation.*;
import org.springframework.web.server.ResponseStatusException; import java.util.*;

@RestController @RequestMapping("/api/complaints") public class FeedbackController {
 private final ComplaintRepository complaints; private final ComplaintFeedbackRepository feedback; private final UserRepository users;
 public FeedbackController(ComplaintRepository c,ComplaintFeedbackRepository f,UserRepository u){complaints=c;feedback=f;users=u;}
 private User citizen(Authentication a){User u=users.findByEmail(a.getName()).orElseThrow(()->new ResponseStatusException(HttpStatus.UNAUTHORIZED,"User not found"));if(!"CITIZEN".equals(u.role))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Citizen access required");return u;}
 @GetMapping("/{id}/feedback") public Map<String,Object> get(@PathVariable Long id,Authentication a){User u=citizen(a);Complaint c=complaints.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Complaint not found"));if(!Objects.equals(c.citizen.id,u.id))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Access denied");return feedback.findByComplaintId(id).map(f->Map.<String,Object>of("rating",f.rating,"comment",f.comment==null?"":f.comment,"createdAt",f.createdAt)).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Feedback not found"));}
 @PostMapping("/{id}/feedback") @ResponseStatus(HttpStatus.CREATED) public Map<String,Object> create(@PathVariable Long id,@RequestBody Map<String,Object> body,Authentication a){User u=citizen(a);Complaint c=complaints.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Complaint not found"));if(!Objects.equals(c.citizen.id,u.id))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Access denied");if(!"RESOLVED".equals(c.status))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Feedback is available after resolution");if(feedback.findByComplaintId(id).isPresent())throw new ResponseStatusException(HttpStatus.CONFLICT,"Feedback has already been submitted");int rating;try{rating=Integer.parseInt(String.valueOf(body.get("rating")));}catch(Exception e){throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Rating must be between 1 and 5");}String comment=Objects.toString(body.get("comment"),"").trim();if(rating<1||rating>5||comment.length()>1000)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Provide a rating from 1 to 5 and feedback up to 1000 characters");ComplaintFeedback f=new ComplaintFeedback();f.complaint=c;f.citizen=u;f.rating=rating;f.comment=comment.isBlank()?null:comment;feedback.save(f);return Map.of("rating",f.rating,"comment",f.comment==null?"":f.comment,"createdAt",f.createdAt);}
}
