import React,{useMemo,useState}from'react';import{createRoot}from'react-dom/client';import{motion,AnimatePresence}from'framer-motion';import{BarChart3,CheckCircle2,Clock3,FileWarning,LogIn,Menu,Plus,Search,ShieldCheck,TrendingUp,X}from'lucide-react';import{Bar,BarChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis,PieChart,Pie,Cell}from'recharts';import'./index.css';
const API=(import.meta.env.VITE_API_URL||'http://localhost:8080/api').replace(/\/$/,'');
const demoComplaints=[
{id:1,trackingNumber:'GRV-2026-1042',title:'Broken street lights on Main Road',category:{name:'Street Lights'},priority:'HIGH',status:'IN_PROGRESS',location:'Main Road',createdAt:'2026-09-14'},
{id:2,trackingNumber:'GRV-2026-1041',title:'Garbage collection delayed',category:{name:'Garbage'},priority:'MEDIUM',status:'UNDER_REVIEW',location:'Ward 12',createdAt:'2026-09-13'},
{id:3,trackingNumber:'GRV-2026-1037',title:'Potholes near bus stop',category:{name:'Roads'},priority:'HIGH',status:'RESOLVED',location:'Central Avenue',createdAt:'2026-09-10'},
{id:4,trackingNumber:'GRV-2026-1030',title:'Water supply interruption',category:{name:'Water Supply'},priority:'URGENT',status:'SUBMITTED',location:'Lake View',createdAt:'2026-09-08'}];
function Button({children,onClick,secondary=false}){return <button onClick={onClick} className={(secondary?'glass text-white':'bg-cyan-300 text-slate-950')+' rounded-xl px-5 py-3 font-bold hover:scale-[1.02] transition'}>{children}</button>}
function Nav({go,user,onLogout}){return <nav className="sticky top-0 z-40 p-4"><div className="glass max-w-7xl mx-auto rounded-2xl px-5 py-3 flex items-center justify-between"><button onClick={()=>go('home')} className="font-black text-xl flex gap-2 items-center"><ShieldCheck className="text-cyan-300"/>CivicResolve</button><div className="hidden md:flex items-center gap-2 text-sm"><button onClick={()=>go('home')} className="px-3 py-2">Home</button><button onClick={()=>go('track')} className="px-3 py-2">Track</button>{user?.role!=='ADMIN'&&<button onClick={()=>go('submit')} className="px-3 py-2">Submit</button>}{user?.role==='ADMIN'&&<button onClick={()=>go('admin')} className="px-3 py-2">Authority</button>}{user?<button onClick={onLogout} className="glass px-4 py-2 rounded-xl">Logout</button>:<Button onClick={()=>go('login')}>Login</Button>}</div><button className="md:hidden"><Menu/></button></div></nav>}
function Home({go}){return <motion.section initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} className="max-w-7xl mx-auto px-5 pt-16 pb-20"><div className="grid lg:grid-cols-[1.15fr_.85fr] gap-12 items-center"><div><span className="glass inline-flex rounded-full px-4 py-2 text-sm text-cyan-200">Transparent civic service platform</span><h1 className="text-6xl md:text-8xl font-black leading-[.9] mt-6">Your voice.<br/><span className="text-cyan-300">Visible action.</span></h1><p className="text-slate-300 text-lg max-w-2xl mt-7 leading-relaxed">Submit public grievances, track progress in real time, and keep authorities accountable with a transparent digital workflow.</p><div className="flex flex-wrap gap-3 mt-8"><Button onClick={()=>go('submit')}><Plus className="inline mr-2" size={18}/>Report an issue</Button><Button secondary onClick={()=>go('track')}>Track complaint</Button></div></div><div className="glass rounded-[32px] p-7"><div className="text-sm text-slate-400">Live service overview</div><div className="grid grid-cols-2 gap-4 mt-5">{[['12,842','Total complaints'],['9,821','Resolved'],['1,245','In progress'],['87','Priority cases']].map(x=><div className="rounded-2xl bg-white/5 p-5"><div className="text-3xl font-black">{x[0]}</div><div className="text-slate-400 text-sm mt-1">{x[1]}</div></div>)}</div><div className="mt-5 rounded-2xl bg-cyan-300/10 border border-cyan-300/10 p-5"><div className="flex items-center gap-3"><CheckCircle2 className="text-cyan-300"/><div><b>Resolution transparency</b><p className="text-sm text-slate-400 mt-1">Every status change can be recorded in the complaint timeline.</p></div></div></div></div></div></motion.section>}
function Auth({mode,go,setUser}){const[form,setForm]=useState({name:'',email:'',password:''});const[msg,setMsg]=useState('');const submit=async e=>{e.preventDefault();setMsg('');try{let endpoint=mode==='login'?'/auth/login':'/auth/register';let body=mode==='login'?{email:form.email,passwordHash:form.password}:{fullName:form.name,email:form.email,passwordHash:form.password};let r=await fetch(API+endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});let d=await r.json();if(!r.ok)throw Error(d.message||'Request failed');if(mode==='login'){localStorage.setItem('token',d.token);setUser({name:d.name,role:d.role,userId:d.userId});go(d.role==='ADMIN'?'admin':'citizen')}else{setMsg('Account created. Please sign in.');go('login')}}catch(e){setMsg(e.message)}};return <section className="max-w-md mx-auto px-5 pt-16"><div className="glass rounded-3xl p-7"><h2 className="text-4xl font-black">{mode==='login'?'Welcome back':'Create account'}</h2><p className="text-slate-400 mt-2">{mode==='login'?'Access your civic workspace.':'Join CivicResolve as a citizen.'}</p><form onSubmit={submit} className="space-y-4 mt-7">{mode==='register'&&<input className="input" placeholder="Full name" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/>}<input className="input" type="email" placeholder="Email address" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input className="input" type="password" placeholder="Password" required minLength="8" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><Button>{mode==='login'?'Sign in':'Create account'}</Button></form>{msg&&<p className="text-cyan-200 mt-4 text-sm">{msg}</p>}<button className="text-sm text-slate-400 mt-6" onClick={()=>go(mode==='login'?'register':'login')}>{mode==='login'?'New here? Create an account':'Already registered? Sign in'}</button></div></section>}
function Track(){const[code,setCode]=useState('');const[data,setData]=useState(null);const[msg,setMsg]=useState('');const go=async()=>{try{let r=await fetch(API+'/complaints/track/'+code);if(!r.ok)throw Error();setData(await r.json());setMsg('')}catch{let c=demoComplaints.find(x=>x.trackingNumber===code);c?setData({complaint:c,history:[{newStatus:'SUBMITTED',comment:'Complaint received'},{newStatus:c.status,comment:'Latest update'}]}):(setData(null),setMsg('No complaint found.'))}};return <section className="max-w-4xl mx-auto px-5 pt-14"><h2 className="text-5xl font-black">Track your complaint</h2><p className="text-slate-400 mt-2">Use the tracking number from your submission.</p><div className="glass rounded-3xl p-5 mt-7 flex gap-3"><input className="input" placeholder="GRV-2026-1042" value={code} onChange={e=>setCode(e.target.value)}/><Button onClick={go}><Search/></Button></div>{msg&&<p className="text-amber-300 mt-4">{msg}</p>}{data&&<div className="glass rounded-3xl p-7 mt-6"><div className="flex flex-wrap justify-between gap-3"><div><div className="text-sm text-cyan-300">{data.complaint.trackingNumber}</div><h3 className="text-2xl font-bold mt-1">{data.complaint.title}</h3></div><span className="bg-cyan-300/15 text-cyan-200 px-3 py-2 rounded-full h-fit">{data.complaint.status}</span></div><p className="text-slate-400 mt-4">{data.complaint.description}</p><div className="border-l border-white/10 ml-3 mt-7 space-y-6">{data.history.map((h,i)=><div className="relative pl-7"><span className="absolute -left-[7px] top-1 w-3 h-3 rounded-full bg-cyan-300"/><b>{h.newStatus}</b><p className="text-sm text-slate-400 mt-1">{h.comment}</p></div>)}</div></div>}</section>}
function Submit({user,go}){const[form,setForm]=useState({title:'',description:'',category:1,priority:'MEDIUM',location:''});const[msg,setMsg]=useState('');const send=async e=>{e.preventDefault();if(!user){go('login');return}try{let r=await fetch(API+'/complaints',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+localStorage.getItem('token')},body:JSON.stringify({...form,citizen:{id:user.userId},category:{id:Number(form.category)}})});let d=await r.json();if(!r.ok)throw Error(d.message||'Could not submit');setMsg('Submitted successfully. Tracking number: '+d.trackingNumber);setForm({title:'',description:'',category:1,priority:'MEDIUM',location:''})}catch(e){setMsg(e.message)}};return <section className="max-w-3xl mx-auto px-5 pt-14"><h2 className="text-5xl font-black">Report a public issue</h2><p className="text-slate-400 mt-2">Provide enough detail for an authority to act quickly.</p><form onSubmit={send} className="glass rounded-3xl p-7 mt-7 space-y-5"><input className="input" placeholder="Complaint title" required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><textarea className="input min-h-40" placeholder="Describe the issue, what happened and where..." required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><div className="grid md:grid-cols-2 gap-4"><select className="input" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{['Roads','Street Lights','Water Supply','Garbage','Drainage','Electricity','Public Safety','Transportation','Other'].map((x,i)=><option className="bg-slate-900" value={i+1}>{x}</option>)}</select><select className="input" value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}>{['LOW','MEDIUM','HIGH','URGENT'].map(x=><option className="bg-slate-900">{x}</option>)}</select></div><input className="input" placeholder="Location / landmark" value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/><Button>Submit grievance</Button>{msg&&<p className="text-cyan-200">{msg}</p>}</form></section>}
function Citizen({user,go}){return <section className="max-w-7xl mx-auto px-5 pt-12"><div className="flex justify-between items-end"><div><div className="text-cyan-300 text-sm">Citizen workspace</div><h2 className="text-5xl font-black mt-1">Hello, {user.name}</h2></div><Button onClick={()=>go('submit')}>+ New complaint</Button></div><div className="grid md:grid-cols-3 gap-4 mt-8">{[['4','Submitted'],['2','In progress'],['8','Resolved']].map(x=><div className="glass rounded-2xl p-6"><div className="text-3xl font-black">{x[0]}</div><div className="text-slate-400">{x[1]}</div></div>)}</div><div className="glass rounded-3xl p-6 mt-6"><h3 className="text-xl font-bold">Recent complaints</h3><div className="mt-4 space-y-3">{demoComplaints.map(c=><div className="rounded-2xl bg-white/5 p-4 flex flex-wrap justify-between gap-3"><div><div className="text-xs text-cyan-300">{c.trackingNumber}</div><b>{c.title}</b><div className="text-sm text-slate-500 mt-1">{c.category.name} · {c.createdAt}</div></div><span className="h-fit rounded-full bg-white/10 px-3 py-1 text-sm">{c.status}</span></div>)}</div></div></section>}
function StatusPill({status}){
 const labels={SUBMITTED:'Submitted',UNDER_REVIEW:'Under review',IN_PROGRESS:'In progress',RESOLVED:'Resolved'};
 return <span className="rounded-full bg-white/10 px-3 py-1 text-xs font-bold">{labels[status]||status}</span>
}
function Admin(){
 const[complaints,setComplaints]=useState([]);
 const[stats,setStats]=useState({total:0,submitted:0,underReview:0,inProgress:0,resolved:0});
 const[selected,setSelected]=useState(null);
 const[newStatus,setNewStatus]=useState('UNDER_REVIEW');
 const[comment,setComment]=useState('');
 const[msg,setMsg]=useState('');
 const[loading,setLoading]=useState(false);
 const token=localStorage.getItem('token');
 const chart=[{name:'Submitted',value:stats.submitted},{name:'Review',value:stats.underReview},{name:'Progress',value:stats.inProgress},{name:'Resolved',value:stats.resolved}];
 const load=async()=>{
  setMsg('');
  try{
   const h={Authorization:'Bearer '+token};
   const[a,r]=await Promise.all([fetch(API+'/admin/analytics',{headers:h}),fetch(API+'/admin/complaints',{headers:h})]);
   if(a.status===403||r.status===403)throw Error('Authority access denied. Please log in again with an ADMIN account.');
   if(!a.ok||!r.ok)throw Error('Could not load authority data.');
   setStats(await a.json());
   setComplaints(await r.json());
  }catch(e){setMsg(e.message)}
 };
 React.useEffect(()=>{load()},[]);
 const openComplaint=(c)=>{setSelected(c);setNewStatus(c.status==='SUBMITTED'?'UNDER_REVIEW':c.status==='UNDER_REVIEW'?'IN_PROGRESS':c.status==='IN_PROGRESS'?'RESOLVED':c.status);setComment('');setMsg('')};
 const updateStatus=async()=>{
  if(!selected)return;
  setLoading(true);setMsg('');
  try{
   const r=await fetch(API+'/admin/complaints/'+selected.id+'/status',{method:'PATCH',headers:{'Content-Type':'application/json','Authorization':'Bearer '+token},body:JSON.stringify({status:newStatus,comment:comment.trim()||'Status updated by authority'})});
   const text=await r.text();
   let d=null;try{d=text?JSON.parse(text):null}catch{}
   if(!r.ok)throw Error(d?.message||text||'Status update failed.');
   setMsg('Status updated successfully.');
   setSelected(d);
   setComplaints(prev=>prev.map(c=>c.id===d.id?d:c));
   setComment('');
   await load();
  }catch(e){setMsg(e.message)}finally{setLoading(false)}
 };
 return <section className="max-w-7xl mx-auto px-5 pt-10 pb-20">
  <div><div className="text-cyan-300 text-sm">Authority console</div><h2 className="text-5xl font-black">Operations dashboard</h2><p className="text-slate-400 mt-2">Review complaints, update progress and keep citizens informed.</p></div>
  {msg&&<div className="mt-5 rounded-2xl border border-cyan-300/20 bg-cyan-300/10 text-cyan-100 px-5 py-4">{msg}</div>}
  <div className="grid grid-cols-2 lg:grid-cols-5 gap-4 mt-8">{[['Total',stats.total],['Submitted',stats.submitted],['Review',stats.underReview],['In progress',stats.inProgress],['Resolved',stats.resolved]].map(x=><div key={x[0]} className="glass rounded-2xl p-5"><div className="text-2xl font-black">{x[1]}</div><div className="text-sm text-slate-400">{x[0]}</div></div>)}</div>
  <div className="grid lg:grid-cols-2 gap-5 mt-5"><div className="glass rounded-3xl p-6"><h3 className="font-bold text-lg">Resolution pipeline</h3><div className="h-72 mt-4"><ResponsiveContainer><BarChart data={chart}><CartesianGrid strokeDasharray="3 3" strokeOpacity={.1}/><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey="value" fill="#67e8f9" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></div></div><div className="glass rounded-3xl p-6"><h3 className="font-bold text-lg">Priority distribution</h3><div className="h-72 mt-4"><ResponsiveContainer><PieChart><Pie data={[{name:'Urgent',value:12},{name:'High',value:28},{name:'Medium',value:42},{name:'Low',value:18}]} dataKey="value" nameKey="name" outerRadius={95} label>{[0,1,2,3].map((_,i)=><Cell key={i} fill={['#fb7185','#fbbf24','#67e8f9','#94a3b8'][i]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></div></div></div>
  <div className="glass rounded-3xl p-6 mt-5"><div className="flex justify-between items-center"><div><h3 className="font-bold text-lg">Complaint queue</h3><p className="text-sm text-slate-500 mt-1">Select a complaint to review and update its status.</p></div><button onClick={load} className="text-sm text-cyan-300">Refresh</button></div><div className="overflow-x-auto mt-4"><table className="w-full text-left text-sm"><thead className="text-slate-500"><tr><th className="py-3">Tracking</th><th>Complaint</th><th>Priority</th><th>Status</th><th>Action</th></tr></thead><tbody>{complaints.map(c=><tr key={c.id} className="border-t border-white/5"><td className="py-4 text-cyan-300">{c.trackingNumber}</td><td><button onClick={()=>openComplaint(c)} className="text-left hover:text-cyan-200"><b>{c.title}</b><div className="text-xs text-slate-500 mt-1">{c.location||'Location not provided'}</div></button></td><td>{c.priority}</td><td><StatusPill status={c.status}/></td><td><button onClick={()=>openComplaint(c)} className="rounded-xl bg-cyan-300 text-slate-950 px-4 py-2 font-bold hover:scale-[1.02] transition">Manage</button></td></tr>)}</tbody></table>{complaints.length===0&&<div className="py-10 text-center text-slate-500">No complaints found.</div>}</div></div>
  <AnimatePresence>{selected&&<motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-50 bg-black/70 backdrop-blur-sm p-4 flex items-center justify-center" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><motion.div initial={{opacity:0,y:20,scale:.98}} animate={{opacity:1,y:0,scale:1}} className="glass w-full max-w-2xl rounded-3xl p-7 max-h-[90vh] overflow-y-auto"><div className="flex justify-between gap-4"><div><div className="text-sm text-cyan-300">{selected.trackingNumber}</div><h3 className="text-3xl font-black mt-1">{selected.title}</h3></div><button onClick={()=>setSelected(null)} className="rounded-xl bg-white/5 p-2"><X/></button></div><div className="grid md:grid-cols-2 gap-4 mt-6"><div className="rounded-2xl bg-white/5 p-4"><div className="text-xs text-slate-500">Category</div><div className="font-bold mt-1">{selected.category?.name||'—'}</div></div><div className="rounded-2xl bg-white/5 p-4"><div className="text-xs text-slate-500">Priority</div><div className="font-bold mt-1">{selected.priority}</div></div><div className="rounded-2xl bg-white/5 p-4 md:col-span-2"><div className="text-xs text-slate-500">Location</div><div className="font-bold mt-1">{selected.location||'Not provided'}</div></div></div><div className="mt-6"><div className="text-sm text-slate-500">Description</div><p className="mt-2 text-slate-200 leading-relaxed">{selected.description||'No description available.'}</p></div><div className="mt-7 border-t border-white/10 pt-6"><h4 className="font-bold text-lg">Update complaint status</h4><div className="grid md:grid-cols-2 gap-4 mt-4"><select className="input" value={newStatus} onChange={e=>setNewStatus(e.target.value)}><option className="bg-slate-900" value="SUBMITTED">Submitted</option><option className="bg-slate-900" value="UNDER_REVIEW">Under review</option><option className="bg-slate-900" value="IN_PROGRESS">In progress</option><option className="bg-slate-900" value="RESOLVED">Resolved</option></select><div className="rounded-xl bg-white/5 px-4 py-3 flex items-center"><StatusPill status={selected.status}/></div></div><textarea className="input min-h-28 mt-4" placeholder="Authority comment for the citizen timeline..." value={comment} onChange={e=>setComment(e.target.value)}/><div className="flex flex-wrap gap-3 mt-4"><button onClick={updateStatus} disabled={loading} className="rounded-xl bg-cyan-300 text-slate-950 px-5 py-3 font-bold disabled:opacity-50">{loading?'Updating...':'Save status update'}</button><button onClick={()=>setSelected(null)} className="glass text-white rounded-xl px-5 py-3 font-bold">Close</button></div></div></motion.div></motion.div>}</AnimatePresence>
 </section>
}
function App(){const[page,setPage]=useState('home');const[user,setUser]=useState(null);const go=p=>setPage(p);const logout=()=>{localStorage.removeItem('token');setUser(null);go('home')};return <><Nav go={go} user={user} onLogout={logout}/><AnimatePresence mode="wait"><div key={page}>{page==='home'&&<Home go={go}/>} {page==='login'&&<Auth mode="login" go={go} setUser={setUser}/>} {page==='register'&&<Auth mode="register" go={go} setUser={setUser}/>} {page==='track'&&<Track/>} {page==='submit'&&<Submit user={user} go={go}/>} {page==='citizen'&&user&&<Citizen user={user} go={go}/>} {page==='admin'&&user&&<Admin go={go}/>}</div></AnimatePresence></>}
createRoot(document.getElementById('root')).render(<App/>);